- hosts: "{{ groups['newmachines'] }}"
  remote_user: "{{ ansible_user }}"
  vars_files: 
    - ./vars/vars.yaml

- name: Run Ensure Root Access
  ansible.builtin.import_playbook: enable-root-access.yaml  
- name: Ensure pip
  ansible.builtin.import_playbook: ensurepip.yaml
- name: Run Install and Setup Miniconda
  ansible.builtin.import_playbook: miniconda.yaml
- name: Run Install and Setup RabbitMQ
  ansible.builtin.import_playbook: rabbitmq.yaml
- name: Run Install and Setup Node and PM2
  ansible.builtin.import_playbook: nodejs.yaml
- name: Ensure UFW permissions
  ansible.builtin.import_playbook: ufw.yaml
- name: Run Coordinator 
  ansible.builtin.import_playbook: coordinator.yaml