- hosts: virtualmachines
  remote_user: "{{ remote_username }}"
  vars_files: 
    - ./vars/vars.yaml
  become: yes

  tasks:
    - name: Install the gpg key for nodejs LTS
      ansible.builtin.apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present

    - name: Install the nodejs LTS repos
      ansible.builtin.apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ ubuntu_version }} main"
        state: present
        update_cache: yes

    - name: Install NodeJS
      tags: nodesjs, install
      ansible.builtin.apt:
        name: nodejs
        state: latest

    - name: Install libcap2-bin
      ansible.builtin.apt:
        name: libcap2-bin
        state: latest

    - name: Setcap for Node
      ansible.builtin.shell: setcap cap_net_bind_service=+ep /usr/bin/node
