- hosts: "{{ groups['vectorizers'] }}"
  remote_user: "{{ ansible_user }}"
  vars_files: 
    - ./vars/vars.yaml

  tasks:
    - name: Copy .env.coordinator
      ansible.builtin.template:
        src: ./.env.coordinator.j2
        dest: "/home/{{ ansible_user }}/.env.coordinator"
    - name: Copy .ecosystem.config.js
      ansible.builtin.template:
        src: ./vectorizer.ecosystem.config.js.j2
        dest: "/home/{{ ansible_user }}/ecosystem.config.js"
    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/Teleoscope/Teleoscope.git'
        dest: ~/Teleoscope