name: Merge Backend into Frontend

on:
  schedule:
    # Runs at 12:00 UTC every day
    - cron: '0 7 * * *'

jobs:
  merge-branches:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Full clone to allow branch merging

    - name: Set up Git user
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Fetch all branches
      run: git fetch origin

    - name: Checkout the frontend branch
      run: git checkout frontend

    - name: Merge backend into frontend
      run: git merge origin/backend

    - name: Push changes to frontend
      run: git push origin frontend
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
