# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: ./frontend

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/



    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: touch .env.local
      working-directory: ./frontend
    - run: echo "MONGODB_URI=test" >> .env.local
      working-directory: ./frontend
    - run: echo "MONGODB_DB=test" >> .env.local
      working-directory: ./frontend
    - run: echo "NEXT_PUBLIC_RABBITMQ_USERNAME=test" >> .env.local
      working-directory: ./frontend
    - run: echo "NEXT_PUBLIC_RABBITMQ_PASSWORD=test" >> .env.local
      working-directory: ./frontend    
    - run: echo "NEXT_PUBLIC_RABBITMQ_VHOST=test" >> .env.local
      working-directory: ./frontend    
    - run: echo "NEXT_PUBLIC_RABBITMQ_HOST=test" >> .env.local
      working-directory: ./frontend    
    - run: npm i -g npm@latest
      working-directory: ./frontend    
    - run: npm run test
      working-directory: ./frontend    
    - run: npm run build --if-present
      working-directory: ./frontend    
